<?php
$page_title       = 'Book Publishing Services - Book Spire Publishing';
$meta_description = 'Full-service book publishing by Book Spire Publishing. From manuscript to global distribution — we handle the entire publishing process for your book.';
$canonical_url    = 'https://bookspirepublishing.com/book-publishing.php';
include 'includes/header.php';
?>


    <script type="application/ld+json">
        {
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": [{
                    "@type": "Question",
                    "name": "Does Amazon offer book publishing services?",
                    "acceptedAnswer": {
                        "@type": "Answer",
                        "text": "It’s a daunting task to publish your book on platforms like Amazon or Barnes&Nobles as you need an expert publisher to assist you in making your book global by publishing your book on Amazon, taking care of all the documentations, copyrights, and IBANs required."
                    }
                },
                {
                    "@type": "Question",
                    "name": "Is Amazon the best place to publish a book?",
                    "acceptedAnswer": {
                        "@type": "Answer",
                        "text": "Amazon is a globally well-known platform and a good choice to publish your author aspirations but there are many other platforms as well to make your book globally available for readers who capture interest in your book."
                    }
                },
                {
                    "@type": "Question",
                    "name": "How do I get into Amazon Publishing?",
                    "acceptedAnswer": {
                        "@type": "Answer",
                        "text": "Signup with Amazon and the platform will assist you with everything itself but the termanoligies they possess might not be understandable but if you acquire expert publisher, they might help you in understanding Amazon at ease."
                    }
                },
                {
                    "@type": "Question",
                    "name": "How do I publish my first book?",
                    "acceptedAnswer": {
                        "@type": "Answer",
                        "text": "Either you can go with the traditional book publishing services or you can eliminate all the hassle by hiring an expert publisher to assist you publish your book globally and help you target a wider audience with your manuscript."
                    }
                },
                {
                    "@type": "Question",
                    "name": "How much do publishers pay you for a book?",
                    "acceptedAnswer": {
                        "@type": "Answer",
                        "text": "Amazon being a publishing platform offers 40-70% of your book royalties and help you take the full advantage of your self-publishing journey and enjoy the conversions that your book was able to attract."
                    }
                }
            ]
        }
    </script>
    <!--FAQPage Code Generated by https://saijogeorge.com/json-ld-schema-generator/faq/-->

    <style>
        /* <!-- 1st section start --> */

        section.main-banner-bg {
            margin: 0px 0 0 !important;
            padding: 60px 0;
            background-size: cover;
            background-repeat: no-repeat
        }

        .main-banner-bg h1 {
            font-size: 40px;
            font-weight: 400;
            color: #fff;
            line-height: 56px
        }

        .ratsite {
            min-height: 45px;
            display: flex;
            align-items: center
        }

        .ratings_cont {
            display: flex;
            align-items: center;
            margin-top: 8px
        }

        .ratings_cont h3 {
            font-size: 28px;
            font-weight: 400;
            color: #fff;
            margin-right: 10px
        }

        .ratings_rate {
            display: block;
            line-height: 15px
        }

        .ratings_cont p {
            font-size: 10px;
            color: #17333c;
            margin-bottom: 0;
            font-weight: 600
        }

        .head-serv-bg h5 {
            color: #73c361;
            padding: 10px 0;
            border-left: 4px solid #73c361;
            padding-left: 11px;
        }

        .btn-3 a,
        .btn-3 button {
            background: #01838c;
            border-radius: 5px;
            color: #fff;
            padding: 10px 30px !important;
            border: 2px solid #ffffff;
            margin: 0 !important;
        }

        .banner-content span {
            color: #00efff;
            font-weight: 600;
        }

        .main-banner-bg p {
            font-size: 18px;
            color: #fff;
        }

        .btn-4 a {
            border: 2px solid #ffffff;
            border-radius: 5px;
            color: #ffffff;
            padding: 10px 20px;
            margin: 0 0 0 15px !important;
            background: #01838c;
            margin-left: 10px !important;
        }

        .my-3 {
            margin-top: 2rem !important;
            margin-bottom: 2rem !important;
        }

        /* <!-- 1st section end --> */

        /* <!-- 9th section start --> */

        .best-selling {
            padding: 50px;
        }

        /* <!-- 9th section end --> */

        /* <!-- 3rd section end --> */
        .feature_sec {
            padding-top: 40px !important;
            padding-bottom: 60px !important;
        }

        .feature_box img {
            margin-bottom: 30px;
        }

        .feature_box h5 {
            font-size: 17px;
            font-weight: 600;
            text-transform: capitalize;
            color: #262626;
            margin-bottom: 18px;
            border-bottom: 1px solid #3d5a80;
            padding-bottom: 18px;
        }

        .feature_box p {
            font-size: 16px;
        }

        .feature_sec {
            padding-top: 40px !important;
            padding-bottom: 60px !important;
        }

        .feature_box img {
            margin-bottom: 30px;
        }

        .feature_box h5 {
            font-size: 17px;
            font-weight: 600;
            text-transform: capitalize;
            color: #262626;
            margin-bottom: 18px;
            border-bottom: 1px solid #3d5a80;
            padding-bottom: 18px;
        }

        .feature_box p {
            font-size: 16px;
        }

        .sec_title h2 {
            margin-bottom: 40px;
            font-size: 30px;
            font-weight: 600;
        }

        /* <!-- 3rd section end --> */

        /* <!-- 5th section end --> */

        .cta-bg {
            background: #00838c;
            padding: 20px 0;
        }

        .cta-head h5 {
            color: #fff;
            padding-bottom: 15px;
            font-size: 30px;
            font-weight: 700;
            text-transform: uppercase;
        }

        .cta-head p {
            font-size: 14px;
            font-weight: 300;
            padding: 0 0 15px;
            color: #fff;
        }

        .edit-img img {
            height: 300px;
        }

        .btn-1 a,
        .btn-1 button {
            background: #17333c;
            border-radius: 5px;
            color: #fff;
            padding: 10px 30px !important;
            border: 2px solid #17333c;
            margin: 0 !important;
        }

        .btn-2 a {
            border: 2px solid #17333c;
            border-radius: 5px;
            color: #17333c;
            padding: 10px 20px;
            margin: 0 0 0 15px !important;
        }

        .cta-call {
            padding-left: 25px;
        }

        .cta-call a {
            color: #201b1c;
            text-decoration: none;
            font-size: 20px;
        }

        /* <!-- 5th section end --> */

        /* <!-- 5th section start --> */
        .amer_data {
            text-align: center;
            padding: 20px 150px;
        }

        .amer_data h3 {
            font-size: 33px;
            font-weight: 700;
            color: black;
        }

        .amer_data p {
            font-size: 14px;
            font-weight: 300;
            margin-top: 17px;
        }

        /* <!-- 5th section end --> */

        /* <!-- 7th section start --> */
        .b_book_img img {
            height: 300px;
        }

        .b_book_img {
            text-align: center;
        }

        .b_book_data h3 {
            font-size: 35px;
            font-weight: 700;
            margin-bottom: 18px;
        }

        .b_book_data p {
            font-size: 14px;
        }

        .book_pera {
            display: flex;
            margin-top: 25px;
            justify-content: space-around;
        }

        .b_bookarea {
            padding: 50px;
        }



        /* <!-- 7th section end --> */

        /* <!-- 10th section start --> */
        .rhyme-cta {
            background-image: url(assets/images/new_sec/cta-bg.webp);
            padding: 30px 0;
            background-image: -moz-linear-gradient(90deg, #154890, #1d6bda 100%);
            background-image: -webkit-linear-gradient(90deg, #154890, #1d6bda 100%);
            background-image: -ms-linear-gradient(90deg, #154890, #1d6bda 100%);
            background-color: rgba(21, 72, 144, .99608);
            background-repeat: no-repeat;
            text-align: center;
            padding: 60px 0 30px;
            position: relative;
            background-size: cover;
        }

        .cta::before {
            content: "";
            position: absolute;
            background: url(assets/images/new_sec/cta-before.webp) center/100% no-repeat;
            width: 600px;
            height: 377px;
            left: 0;
            bottom: -22%;
            background-position-x: -31px;
            top: -1%;
            background-size: 70%;
        }

        .rhyme-cta::after {
            width: 327px;
            background-size: cover;
            height: 333px;
            background-position-x: 0;
            top: 71%;
            background-position: right;
            background-image: url(assets/images/new_sec/cta-after.webp);
            content: "";
            position: absolute;
            background: url(assets/images/new_sec/cta-after.webp) center/cover no-repeat;
            right: 0;
            transform: translateY(-50%);
        }

        .cta-hdg>h4 {
            color: #fff;
            font-size: 36px;
            margin-bottom: 15px;
            font-weight: 400;
        }

        .rhyme-cta .cta-hdg p {
            margin-bottom: 40px;
            color: #fff;
            font-size: 18px;
            line-height: 22px;
        }

        .default_btn {
            font-size: 14px;
            padding: 9px 15px;
            margin-right: 20px;
            background-color: #000;
            color: #fff;
            font-weight: 600;
            padding: 11px 30px;
            font-family: 'Poppins', sans-serif;
            border-radius: 100px;
            transition: all 0.25s ease-in-out;
        }

        /* <!-- 10th section end --> */

        /* <!-- 11th section start --> */
        .frequently-asked-questions .frequently-heading {
            text-align: center;
        }

        .frequently-asked-questions .frequently-heading h3,
        .frequently-heading h5 {
            font-family: Poppins, sans-serif;
            text-align: center;
            font-weight: 700;
            text-transform: capitalize;
            margin: 30px 0;
            font-size: 46px;
            color: #00112b;
            width: 75%;
            margin: 20px auto 20px;

        }

        .frequently-asked-questions .frequently-heading p {
            font-family: Poppins, sans-serif;

            font-size: 18.01px;

            margin: 0 0 45px;
            color: #353a4d;
            font-weight: 500;
        }

        .frequently-asked-questions .frequently-heading p span {
            display: block;
        }

        .faq_sec {
            width: 80%;
            text-align: center;
            margin: 0 auto;
            padding: 50px;
        }

        /* <!-- 11th section end --> */
    </style>


    <!-- 1st section start content done-->
    <section class="main-banner-bg head-serv-bg" style="background-image: url(assets/images/new_sec/s-banner-bg.webp);">
        <div class="container">
            <div class="row">
                <div class="col-md-6  my-auto">
                    <div class="banner-content">
                        <h1>USA Book Publishing Agency For Your <span class="aner_con">Author Journey</span></h1>
                        <p>We are an expert book publishing company that has the expertise to walk you through the entire book publishing process so that you can have full control over your author journey without having to deal with obnoxious traditional book publishing houses. Get expert ebook publishing services to elevate a hassle-free author journey and fulfill your dreams on the go. Collaborate with an affordable self-publishing eBook company that has the expertise to simplify the book publishing process for you.</p>
                        <div class="d-flex my-3 bane_btns">
                            <div class="btn-3">
                                <a href="javascript:" class="btn  various btn-home" data-fancybox="" data-src="#popupform">Get a Free Quote</a>
                            </div>
                            <div class="btn-4">
                                <a href="javascript:" class="btn btn-transparent chat chat">Live Chat</a>
                            </div>
                        </div>
                        <div class="banner-bages">
                            <div class="owl-carousel bages-carousel owl-theme owl-loaded owl-drag">

                                <div class="owl-stage-outer">
                                    <div class="owl-stage" style="transform: translate3d(0px, 0px, 0px); transition: all 0s ease 0s; width: 646px;">
                                        <!-- <div class="owl-item active" style="width: 151.5px; margin-right: 10px;">
                                        <div class="item">
                                            <a href="https://www.trustpilot.com/review/bookspirepublishing.com">
                                                <div class="ratsite">
                                                    <img loading="lazy" src="assets/images/new_sec/trustpilot.webp" alt="review_icon">
                                                </div>
                                                <div class="ratings_cont">
                                                    <h3>4.6</h3>
                                                    <div class="ratings_rate">
                                                        <img loading="lazy" src="assets/images/new_sec/rating-half.webp" class="img-fluid" alt="TWT imgs">
                                                        <p>Ratings</p>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                    </div> -->
                                        <div class="owl-item active" style="width: 151.5px; margin-right: 10px;">
                                            <div class="item">
                                                <a href="https://www.bark.com/en/us/company/the-writers-tree/mpJny/">
                                                    <div class="ratsite">
                                                        <img loading="lazy" src="assets/images/new_sec/bark.webp" class="img-fluid" alt="TWT imgs">
                                                    </div>
                                                    <div class="ratings_cont">
                                                        <h3>5.0</h3>
                                                        <div class="ratings_rate">
                                                            <img loading="lazy" src="assets/images/new_sec/rating-full.webp" class="img-fluid" alt="TWT imgs">
                                                            <p>Ratings</p>
                                                        </div>
                                                    </div>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="owl-item active" style="width: 151.5px; margin-right: 10px;">
                                            <div class="item">
                                                <a href="https://clutch.co/profile/writers-tree">
                                                    <div class="ratsite">
                                                        <img loading="lazy" src="assets/images/new_sec/clutch.webp" class="img-fluid" alt="TWT imgs">
                                                    </div>
                                                    <div class="ratings_cont">
                                                        <h3>5.0</h3>
                                                        <div class="ratings_rate">
                                                            <img loading="lazy" src="assets/images/new_sec/rating-full.webp" class="img-fluid" alt="TWT imgs">
                                                            <p>Ratings</p>
                                                        </div>
                                                    </div>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="owl-item active" style="width: 151.5px; margin-right: 10px;">
                                            <div class="item">
                                                <a href="https://www.sitejabber.com/reviews/bookspirepublishing.com">
                                                    <div class="ratsite">
                                                        <img loading="lazy" src="assets/images/site-jabbar.svg" class="img-fluid" alt="TWT imgs">
                                                    </div>
                                                    <div class="ratings_cont">
                                                        <h3>4.9</h3>
                                                        <div class="ratings_rate">
                                                            <img loading="lazy" src="assets/images/new_sec/rating-almost-full.webp" alt="ratings">
                                                            <p>Ratings</p>
                                                        </div>
                                                    </div>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="owl-nav disabled"><button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button><button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button></div>
                                <div class="owl-dots disabled"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 m-auto">
                    <div class="">
                        <img loading="lazy" src="assets/images/3.webp" class="img-fluid" alt="TWT imgs">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- 1st section end -->

    <section class="site-logos text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-2">
                    <h3>
                        Sell Your <br>
                        Books On
                    </h3>
                </div>
                <div class="col-md-10">
                    <div class="owl-site-logo2 owl-carousel owl-theme">
                        <div class="item">
                            <img src="assets/images/site-logo3.webp" alt="twt_img">
                        </div>
                        <div class="item">
                            <img src="assets/images/site-logo4.webp" alt="twt_img">
                        </div>
                        <div class="item">
                            <img src="assets/images/site-logo5.webp" alt="twt_img">
                        </div>
                        <div class="item">
                            <img src="assets/images/site-logo6.webp" alt="twt_img">
                        </div>
                        <div class="item">
                            <img src="assets/images/site-logo7.webp" alt="twt_img">
                        </div>
                        <div class="item">
                            <img src="assets/images/site-logo8.webp" alt="twt_img">
                        </div>
                        <div class="item">
                            <img src="assets/images/site-logo9.webp" alt="twt_img">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="our-expert">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <h2 class="heading">Best Book Publishers For Hire</h2>
                    <h4>Have the Comfort that your Book is in Safe Hands and Trust a Self-Publishing ebook Company with your very Own Manuscript.</h4>
                    <p>Our Amazon Book Publishers have the expertise to bring your visions to life and we own our promises! Yes, you read it right, We are a team of book publishing experts that has been able to serve numerous clients with tremendous results. You can identify us as an affordable book publishing company that has been able to team up with professional book publishers from the industry to help you publish your book globally, hassle-free. The top USA book publishing agency near you is a life-saver for all aspiring as well as established authors to outshine the publishing industry.</p>
                    <div class="btn-block">
                        <a href="javascript:" class="btn btn-black various" data-fancybox="" data-src="#popupform">Get a
                            Free Quote</a>
                        <a href="javascript:" class="btn btn-transparent chat">Live Chat</a>
                    </div>
                </div>
                <div class="col-md-6 offset-md-1">
                    <div class="row top_space">
                        <div class="col-md-6">
                            <div class="info-expert">
                                <span>
                                    <i class="fas fa-check"></i>
                                </span>
                                <h4>
                                    A number of printed copies of your book
                                </h4>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="info-expert">
                                <span>
                                    <i class="fas fa-check"></i>
                                </span>
                                <h4>
                                    EBook conversion and distribution
                                </h4>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="info-expert">
                                <span>
                                    <i class="fas fa-check"></i>
                                </span>
                                <h4>
                                    Print-on-demand distribution
                                </h4>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="info-expert">
                                <span>
                                    <i class="fas fa-check"></i>
                                </span>
                                <h4>
                                    Certified ISBN barcodes
                                </h4>
                            </div>
                        </div>
                    </div>
                    <h5>
                        Services Include
                    </h5>
                </div>
            </div>
        </div>
    </section>

    <!-- 3rd section start -->
    <section class="feature_sec sec_pt sec_pb">
        <div class="container">
            <div class="sec_title text-center aos-init aos-animate" data-aos="fade-down" data-aos-duration="1500">
                <h2>Online Book Publishing Experts For Hire Online</h2>
            </div>
            <div class="row feature_sec_Slider">
                <div class="col-lg-3 col-md-6 col-sm-6 aos-init aos-animate" data-aos="fade-right" data-aos-delay="200" data-aos-duration="1500">
                    <div class="feature_box">
                        <img src="assets/images/new_sec/feature_icon1.png" alt="twt_img">
                        <h5>Distribution & Retail
                        </h5>
                        <p>Our team of expert book publishers ensures that your book is published on all the major platforms like Amazon, Barnes & Noble, Apple Books, and more.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 aos-init aos-animate" data-aos="fade-right" data-aos-delay="500" data-aos-duration="1500">
                    <div class="feature_box">
                        <img src="assets/images/new_sec/feature_icon2.png" alt="twt_img">
                        <h5>Catalogue of Copyright</h5>
                        <p>Book Spire Publishing will take care of all the copyright registrations, as well as the ISBN and other aspects required for your book.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 aos-init aos-animate" data-aos="fade-right" data-aos-delay="800" data-aos-duration="1500">
                    <div class="feature_box">
                        <img src="assets/images/new_sec/feature_icon3.png" alt="twt_img">
                        <h5>Area of Expertise</h5>
                        <p>USA Book Publishing Agency serves you with a large network of industry specialists including literary, publishing, and media agencies.
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 aos-init aos-animate" data-aos="fade-right" data-aos-delay="1100" data-aos-duration="1500">
                    <div class="feature_box">
                        <img src="assets/images/new_sec/feature_icon4.png" alt="twt_img">
                        <h5>Proven Outcomes</h5>
                        <p>Our result-driven approach is what separates us from others in the market and with the help of our expert book publishers, we have been able to showcase our results time and time again.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- 3rd section end -->

    <!-- 5th section start content done-->
    <section class="cta-bg">
        <div class="container">
            <div class="row">
                <div class="col-md-8 my-auto">
                    <div class="cta-head">
                        <h5>Expert Book Publishers For Hire - Enhancing Your Author Journey, With Professional Book Publishing Team In The USA!</h5>
                        <p>We are a professional team of ebook publishers online, who aim to assist you in elevating your reader’s experience in an uplifting manner. It won’t be wrong if you consider us one of the top Amazon book publishing company in the USA. Let the best book proofreading services help you engage with your readers better.
                        </p>
                    </div>
                    <div class="d-flex mt-md-3">
                        <div class="btn-1">
                            <a href="javascript:" class="btn  various btn-home" data-fancybox="" data-src="#popupform">GET A QUOTE</a>
                        </div>
                        <div class="btn-2">
                            <a href="javascript:" class="btn btn-transparent chat chat">Live Chat</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="edit-img">
                        <img loading="lazy" src="assets/images/new_sec/wri-edi-simg.webp" class="img-fluid" alt="cta_img">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- 5th section end -->

    <!-- 5th section start -->
    <section>
        <div class="contaienr">
            <div class="row">
                <div class="col-sm-12">
                    <div class="amer_data">
                        <h3>Helping Authors Uplift Their Literary Journey, Expert Book Publishing Services Online!</h3>
                        <p>Do you also aspire to turn your ideas into an eBook that captivates readers globally? We are a USA-based eBook publishing service that aims to assist authors globally and help them reach another level of literature excellence. Hire expert book publishers who own diverse expertise in the publishing industry and know how to make your book outshine the industry by making relevant keyword tagging a part of your book publishing process. Get custom online ebook publishing assistance, and packages that cater to your author needs, Elevate your composition with the superior knowledge and skills of our expert publishing services.</p>
                        <p>To target a wider audience and increase the readability of your book with the best Amazon book publishing services online. We are a professional book publishing firm that has the expertise to simplify the publishing process for you.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- 5th section end -->

    <section class="our-shelf">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <h2 class="heading"> Best Book Publishing Services
                        <span>In The USA</span>
                    </h2>
                    <h3>Six easy steps to get your book published</h3>
                    <a href="javascript:" class="btn chat">Get in Touch with us</a>
                </div>
                <div class="col-md-7">
                    <div class="row top_space">
                        <div class="col-md-6">
                            <h5>01</h5>
                            <p>
                                <span>Sign Up</span>
                                According to your needs, choosing your desired book publishing company is the first step.
                            </p>
                        </div>
                        <div class="col-md-6">
                            <h5>02</h5>
                            <p>
                                <span>Manuscript Review</span>
                                Your book will be assigned to a professional editor to eliminate all the errors in your manuscript.
                            </p>
                        </div>

                        <div class="col-md-6">
                            <h5>03</h5>
                            <p>
                                <span>Formatting & Proofreading
                                </span>
                                The third phase involves final proofreading and any necessary formatting.
                            </p>
                        </div>
                        <div class="col-md-6">
                            <h5>04</h5>
                            <p>
                                <span>Book Cover Design</span>
                                It is essential to have a creative book cover design to captivate readers instantly.
                            </p>
                        </div>

                        <div class="col-md-6">
                            <h5>05</h5>
                            <p>
                                <span>Publishing</span>
                                Now, we are on to the final stages of the process, A self-publishing eBook company can help you target a global audience by publishing your book on platforms like Amazon, Barnes & Noble, Kobo, Blurb, and more.
                            </p>
                        </div>
                        <div class="col-md-6">
                            <h5>06</h5>
                            <p>
                                <span>Royalties</span>
                                All that is left now, is for you to sit back, relax, and take pleasure in the royalties generated by your published book.
                            </p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- 7th section start -->
    <section>
        <div class="b_bookarea">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="b_book_img">
                            <img loading="lazy" src="assets/images/Publishing/11.png" class="img-fluid" alt="twt_img">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="b_book_data">
                            <h3>Have a Look at the Professional Amazon Book Publishing Services that We Offer.</h3>
                            <p>We are an ebook publishing service provider in the USA that only teams up with professional publishers who are experienced in looking after your manuscript and ensure that your book is distributed globally targeting a wider audience than you ever imagined. A team of USA book publishers for hire who are experienced in dealing with extensive workloads, and a variety of genres, ensuring the best shape of your manuscript.
                            </p>
                            <div class="book_pera">
                                <ul>
                                    <li>Global Book Publishing Services</li>
                                    <li>Professional Audiobooks</li>
                                    <li>Best Web-Design & Internet SEO</li>
                                </ul>
                                <ul>
                                    <li>Publishing Assistance</li>
                                    <li>Video Book Trailers</li>
                                    <li>Branding and Marketing Campaigns</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- 7th section end -->

    <!-- 10th section start content done-->
    <section class="cta nonfiction-writing-cta rhyme-cta">
        <div class="container-xl">
            <div class="cta-hdg">
                <h4 data-aos="fade-up" class="aos-init aos-animate">Looking for Professional Book Publishers?</h4>
                <p data-aos="fade-up" class="aos-init aos-animate">We can be considered the best book publishing agency in the USA, <br> as we have been able to assist many aspiring authors to establish <br> their dreams and stand out in the publishing industry.</p>
                <div class="cta-btns">
                    <a href="javascript:" class="default_btn orange_btn btn_space hvr-radial-in open_popup" data-fancybox="" data-src="#popupform">Let's Get Started</a>
                    <a href="tel:+12137841841" class="default_btn">Call</a>
                    <a href="javascript:" class="default_btn orange_btn btn_space hvr-radial-in open_popup">Live Chat</a>
                </div>
            </div>
        </div>
    </section>
    <!-- 10th section end -->

    <!-- 11th section start content done-->
    <div class="contaienr faq_sec">
        <div class="row">
            <div class="col-sm-12">
                <div class="frequently-heading">
                    <h3>FAQs</h3>
                    <p>Here’s a list of frequently asked questions you might have about our book writing company.</p>
                </div>

                <div class="accordion" id="faq">
                    <div class="card">
                        <div class="card-header" id="faqhead1">
                            <a style="background: #307d82; color: white; padding: 15px;" href="#" class="btn btn-header-link collapsed" data-toggle="collapse" data-target="#faq1" aria-expanded="false" aria-controls="faq1">Does Amazon offer book publishing services?</a>
                        </div>

                        <div id="faq1" class="collapse" aria-labelledby="faqhead1" data-parent="#faq" style="">
                            <div class="card-body">
                                <p>It’s a daunting task to publish your book on platforms like Amazon or Barnes&Nobles as you need an expert publisher to assist you in making your book global by publishing your book on Amazon, taking care of all the documentations, copyrights, and IBANs required.
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="card">
                        <div class="card-header" id="faqhead2">
                            <a style="background: #307d82; color: white; padding: 15px;" href="#" class="btn btn-header-link collapsed" data-toggle="collapse" data-target="#faq2" aria-expanded="true" aria-controls="faq2">Is Amazon the best place to publish a book?
                            </a>
                        </div>

                        <div id="faq2" class="collapse" aria-labelledby="faqhead2" data-parent="#faq">
                            <div class="card-body">
                                <p>Amazon is a globally well-known platform and a good choice to publish your author aspirations but there are many other platforms as well to make your book globally available for readers who capture interest in your book.
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="card">
                        <div class="card-header" id="faqhead3">
                            <a style="background: #307d82; color: white; padding: 15px;" href="#" class="btn btn-header-link collapsed" data-toggle="collapse" data-target="#faq3" aria-expanded="true" aria-controls="faq3">How do I get into Amazon Publishing?
                            </a>
                        </div>

                        <div id="faq3" class="collapse" aria-labelledby="faqhead3" data-parent="#faq">
                            <div class="card-body">
                                <p>Signup with Amazon and the platform will assist you with everything itself but the termanoligies they possess might not be understandable but if you acquire expert publisher, they might help you in understanding Amazon at ease. </p>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" id="faqhead4">
                            <a style="background: #307d82; color: white; padding: 15px;" href="#" class="btn btn-header-link collapsed" data-toggle="collapse" data-target="#faq4" aria-expanded="true" aria-controls="faq4">How do I publish my first book?
                            </a>
                        </div>

                        <div id="faq4" class="collapse" aria-labelledby="faqhead4" data-parent="#faq">
                            <div class="card-body">
                                <p>Either you can go with the traditional book publishing services or you can eliminate all the hassle by hiring an expert publisher to assist you publish your book globally and help you target a wider audience with your manuscript.
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" id="faqhead5">
                            <a style="background: #307d82; color: white; padding: 15px;" href="#" class="btn btn-header-link collapsed" data-toggle="collapse" data-target="#faq5" aria-expanded="true" aria-controls="faq5">How much do publishers pay you for a book?</a>
                        </div>

                        <div id="faq5" class="collapse" aria-labelledby="faqhead5" data-parent="#faq">
                            <div class="card-body">
                                <p>Amazon being a publishing platform offers 40-70% of your book royalties and help you take the full advantage of your self-publishing journey and enjoy the conversions that your book was able to attract.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- 11th section end -->

    <!-- ── Section 12: Testimonials ── -->
<style>
  .rev-section {
    background: linear-gradient(145deg,#003d45 0%,#005f6b 40%,#00838c 100%);
    padding: 70px 40px 60px;
    position: relative;
    overflow: hidden;
  }

  /* heading */
  .rev-head {
    text-align: center;
    margin-bottom: 44px;
    position: relative;
    z-index: 2;
  }
  .rev-badge {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    background: rgba(255,255,255,.1);
    border: 1px solid rgba(255,255,255,.2);
    border-radius: 100px;
    padding: 5px 16px;
    margin-bottom: 16px;
  }
  .rev-badge span {
    font-size: 11px;
    font-weight: 600;
    letter-spacing: .1em;
    text-transform: uppercase;
    color: #00c4d0;
  }
  .rev-badge svg { width:11px; height:11px; fill:#f3c84a; }
  .rev-head h2 {
    font-size: clamp(28px,4vw,52px);
    font-weight: 800;
    color: #fff;
    margin: 0 0 10px;
    line-height: 1.1;
  }
  .rev-head h2 em { font-style: italic; color: #00c4d0; }
  .rev-head p {
    font-size: 15px;
    color: rgba(255,255,255,.6);
    margin: 0 auto;
    max-width: 460px;
    line-height: 1.6;
  }

  /* slider */
  .rev-viewport {
    overflow: hidden;
    position: relative;
    z-index: 2;
    border-radius: 12px;
  }
  .rev-track {
    display: flex;
    gap: 22px;
    transition: transform .48s cubic-bezier(.4,0,.2,1);
    will-change: transform;
    align-items: stretch;
  }

  /* card */
  .rev-card {
    background: #fff;
    border-radius: 12px;
    padding: 26px 24px 22px;
    display: flex;
    flex-direction: column;
    box-shadow: 0 6px 32px rgba(0,0,0,.14);
    position: relative;
    overflow: hidden;
    box-sizing: border-box;
    flex-shrink: 0;
    transition: transform .25s ease, box-shadow .25s ease;
  }
  .rev-card::before {
    content: '';
    position: absolute;
    top: 0; left: 0; right: 0;
    height: 4px;
    background: linear-gradient(90deg,#00838c,#00c4d0);
    border-radius: 12px 12px 0 0;
  }
  .rev-card:hover {
    transform: translateY(-5px);
    box-shadow: 0 16px 48px rgba(0,0,0,.2);
  }

  /* card internals */
  .rev-q {
    width: 36px; height: 36px;
    background: linear-gradient(135deg,#00838c,#004f57);
    border-radius: 8px;
    display: flex; align-items: center; justify-content: center;
    margin-bottom: 12px;
    flex-shrink: 0;
  }
  .rev-q svg { width:16px; height:16px; fill:#fff; }
  .rev-stars { display:flex; gap:3px; margin-bottom:12px; }
  .rev-stars svg { width:13px; height:13px; fill:#f3c84a; }
  .rev-card p {
    font-size: 14px;
    line-height: 1.75;
    color: #4a4a4a;
    margin: 0;
    flex: 1;
  }
  .rev-author {
    margin-top: 18px;
    padding-top: 14px;
    border-top: 1px solid #eee;
    display: flex;
    align-items: center;
    gap: 10px;
  }
  .rev-avatar {
    width: 40px; height: 40px;
    border-radius: 50%;
    background: linear-gradient(135deg,#00838c,#004f57);
    color: #fff;
    font-weight: 700;
    font-size: 14px;
    display: flex; align-items: center; justify-content: center;
    flex-shrink: 0;
  }
  .rev-author-info h6 {
    font-size: 14px; font-weight: 700; color: #1a1a1a;
    margin: 0 0 2px;
  }
  .rev-author-info span { font-size: 11px; color: #999; }

  /* controls */
  .rev-controls {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 14px;
    margin-top: 36px;
    position: relative;
    z-index: 2;
  }
  .rev-btn {
    width: 44px; height: 44px;
    border-radius: 50%;
    border: 2px solid rgba(255,255,255,.35);
    background: rgba(255,255,255,.1);
    color: #fff;
    cursor: pointer;
    display: flex; align-items: center; justify-content: center;
    transition: background .2s, border-color .2s, transform .2s;
    outline: none;
    flex-shrink: 0;
  }
  .rev-btn:hover { background: rgba(255,255,255,.25); border-color:#fff; transform:scale(1.08); }
  .rev-btn svg { width:16px; height:16px; stroke:#fff; fill:none; stroke-width:2.5; stroke-linecap:round; stroke-linejoin:round; }

  .rev-dots { display:flex; gap:7px; align-items:center; }
  .rev-dot {
    width: 8px; height: 8px;
    border-radius: 50%;
    background: rgba(255,255,255,.3);
    border: none; cursor: pointer; padding: 0;
    transition: all .22s ease;
  }
  .rev-dot.on { background:#fff; width:24px; border-radius:4px; }

  .rev-count { font-size:12px; font-weight:600; color:rgba(255,255,255,.5); min-width:44px; text-align:center; }

  @media (max-width:767px) {
    .rev-section { padding: 50px 20px 44px; }
  }
  @media (max-width:480px) {
    .rev-section { padding: 40px 14px 36px; }
    .rev-btn { width:38px; height:38px; }
    .rev-controls { gap:10px; margin-top:26px; }
  }
</style>

<section class="rev-section">

  <div class="rev-head">
    <div class="rev-badge">
      <svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg>
      <svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg>
      <svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg>
      <svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg>
      <svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg>
      <span>5.0 &middot; 200+ Verified Reviews</span>
    </div>
    <h2>What Our <em>Authors</em> Say</h2>
    <p>Real stories from real authors who trusted Book Spire Publishing to bring their vision to life.</p>
  </div>

  <div class="rev-viewport" id="revViewport">
    <div class="rev-track" id="revTrack">

      <div class="rev-card">
        <div class="rev-q"><svg viewBox="0 0 24 24"><path d="M14.017 21v-7.391c0-5.704 3.748-9.57 8.983-10.609l.995 2.151c-2.432.917-3.995 3.638-3.995 5.849h4v10h-9.983zm-14.017 0v-7.391c0-5.704 3.748-9.57 8.983-10.609l.995 2.151c-2.432.917-3.995 3.638-3.995 5.849h3.983v10h-9.966z"/></svg></div>
        <div class="rev-stars"><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg></div>
        <p>They served me with tremendous ghostwriting services. Being a working woman, I could hardly manage time to complete my book &mdash; thanks to Book Spire Publishing, their team has the diverse experience to write your aspirations with literary excellence.</p>
        <div class="rev-author"><div class="rev-avatar">TH</div><div class="rev-author-info"><h6>Tamatha M. Harkins</h6><span>Verified Author</span></div></div>
      </div>

      <div class="rev-card">
        <div class="rev-q"><svg viewBox="0 0 24 24"><path d="M14.017 21v-7.391c0-5.704 3.748-9.57 8.983-10.609l.995 2.151c-2.432.917-3.995 3.638-3.995 5.849h4v10h-9.983zm-14.017 0v-7.391c0-5.704 3.748-9.57 8.983-10.609l.995 2.151c-2.432.917-3.995 3.638-3.995 5.849h3.983v10h-9.966z"/></svg></div>
        <div class="rev-stars"><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg></div>
        <p>Best ghostwriters in town! They transformed my rough write-ups into a polished, error-free book and helped me execute everything in a very short span of time. Absolutely blown away.</p>
        <div class="rev-author"><div class="rev-avatar">TM</div><div class="rev-author-info"><h6>Tom J. Moore</h6><span>Published Author</span></div></div>
      </div>

      <div class="rev-card">
        <div class="rev-q"><svg viewBox="0 0 24 24"><path d="M14.017 21v-7.391c0-5.704 3.748-9.57 8.983-10.609l.995 2.151c-2.432.917-3.995 3.638-3.995 5.849h4v10h-9.983zm-14.017 0v-7.391c0-5.704 3.748-9.57 8.983-10.609l.995 2.151c-2.432.917-3.995 3.638-3.995 5.849h3.983v10h-9.966z"/></svg></div>
        <div class="rev-stars"><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg></div>
        <p>I'm thoroughly impressed by the creative minds at Book Spire Publishing. I brought a raw concept and they did complete creative justice to it &mdash; beyond anything I imagined.</p>
        <div class="rev-author"><div class="rev-avatar">NM</div><div class="rev-author-info"><h6>Nicolas McCormick</h6><span>First-Time Author</span></div></div>
      </div>

      <div class="rev-card">
        <div class="rev-q"><svg viewBox="0 0 24 24"><path d="M14.017 21v-7.391c0-5.704 3.748-9.57 8.983-10.609l.995 2.151c-2.432.917-3.995 3.638-3.995 5.849h4v10h-9.983zm-14.017 0v-7.391c0-5.704 3.748-9.57 8.983-10.609l.995 2.151c-2.432.917-3.995 3.638-3.995 5.849h3.983v10h-9.966z"/></svg></div>
        <div class="rev-stars"><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg></div>
        <p>Professional, streamlined, meticulous, and creative &mdash; the team at Book Spire Publishing are my go-to for anything I want written and published. Truly world-class service.</p>
        <div class="rev-author"><div class="rev-avatar">AL</div><div class="rev-author-info"><h6>Angelo Long</h6><span>Repeat Client</span></div></div>
      </div>

      <div class="rev-card">
        <div class="rev-q"><svg viewBox="0 0 24 24"><path d="M14.017 21v-7.391c0-5.704 3.748-9.57 8.983-10.609l.995 2.151c-2.432.917-3.995 3.638-3.995 5.849h4v10h-9.983zm-14.017 0v-7.391c0-5.704 3.748-9.57 8.983-10.609l.995 2.151c-2.432.917-3.995 3.638-3.995 5.849h3.983v10h-9.966z"/></svg></div>
        <div class="rev-stars"><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg></div>
        <p>So lucky to have discovered Book Spire Publishing. Their writing team is phenomenal and I'm definitely bringing more projects to them. Can't recommend them enough!</p>
        <div class="rev-author"><div class="rev-avatar">MG</div><div class="rev-author-info"><h6>Malcolm Gibbs</h6><span>Verified Author</span></div></div>
      </div>

      <div class="rev-card">
        <div class="rev-q"><svg viewBox="0 0 24 24"><path d="M14.017 21v-7.391c0-5.704 3.748-9.57 8.983-10.609l.995 2.151c-2.432.917-3.995 3.638-3.995 5.849h4v10h-9.983zm-14.017 0v-7.391c0-5.704 3.748-9.57 8.983-10.609l.995 2.151c-2.432.917-3.995 3.638-3.995 5.849h3.983v10h-9.966z"/></svg></div>
        <div class="rev-stars"><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><svg viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg></div>
        <p>From the first consultation to the final manuscript, every step was handled with professionalism and care. Book Spire Publishing turned my scattered notes into a polished, publishable book.</p>
        <div class="rev-author"><div class="rev-avatar">RD</div><div class="rev-author-info"><h6>Rachel Donovan</h6><span>Published Author</span></div></div>
      </div>

    </div>
  </div>

  <div class="rev-controls">
    <button class="rev-btn" id="revPrev" aria-label="Previous">
      <svg viewBox="0 0 24 24"><polyline points="15 18 9 12 15 6"/></svg>
    </button>
    <div class="rev-dots" id="revDots"></div>
    <span class="rev-count" id="revCount"></span>
    <button class="rev-btn" id="revNext" aria-label="Next">
      <svg viewBox="0 0 24 24"><polyline points="9 18 15 12 9 6"/></svg>
    </button>
  </div>

</section>

<script>
(function () {
  var GAP      = 22;
  var viewport = document.getElementById('revViewport');
  var track    = document.getElementById('revTrack');
  var dotsEl   = document.getElementById('revDots');
  var countEl  = document.getElementById('revCount');
  var cards    = track.querySelectorAll('.rev-card');
  var total    = cards.length;
  var cur      = 0;

  function getCols() {
    var w = window.innerWidth;
    return w >= 1024 ? 3 : w >= 600 ? 2 : 1;
  }

  function setWidths() {
    var cols  = getCols();
    var cardW = Math.floor((viewport.offsetWidth - GAP * (cols - 1)) / cols);
    [].forEach.call(cards, function (c) { c.style.width = cardW + 'px'; });
    return cardW;
  }

  function buildDots() {
    var max = total - getCols();
    dotsEl.innerHTML = '';
    for (var i = 0; i <= max; i++) {
      var d = document.createElement('button');
      d.className = 'rev-dot' + (i === cur ? ' on' : '');
      d.setAttribute('aria-label', 'Review ' + (i + 1));
      (function (n) { d.addEventListener('click', function () { go(n); }); })(i);
      dotsEl.appendChild(d);
    }
  }

  function go(idx) {
    var cols  = getCols();
    var max   = total - cols;
    cur = ((idx % (max + 1)) + (max + 1)) % (max + 1);
    var cardW  = setWidths();
    track.style.transform = 'translateX(-' + cur * (cardW + GAP) + 'px)';
    dotsEl.querySelectorAll('.rev-dot').forEach(function (d, i) {
      d.classList.toggle('on', i === cur);
    });
    countEl.textContent = (cur + 1) + ' / ' + (max + 1);
  }

  function init() {
    setWidths();
    buildDots();
    go(cur);
  }

  document.getElementById('revPrev').addEventListener('click', function () { go(cur - 1); });
  document.getElementById('revNext').addEventListener('click', function () { go(cur + 1); });

  var sx = 0;
  viewport.addEventListener('touchstart', function (e) { sx = e.touches[0].clientX; }, { passive: true });
  viewport.addEventListener('touchend',   function (e) {
    var dx = e.changedTouches[0].clientX - sx;
    if (Math.abs(dx) > 40) go(dx < 0 ? cur + 1 : cur - 1);
  });

  var t = setInterval(function () { go(cur + 1); }, 5000);
  viewport.addEventListener('mouseenter', function () { clearInterval(t); });
  viewport.addEventListener('mouseleave', function () { t = setInterval(function () { go(cur + 1); }, 5000); });

  var rt;
  window.addEventListener('resize', function () {
    clearTimeout(rt);
    rt = setTimeout(function () { cur = Math.min(cur, total - getCols()); init(); }, 150);
  });

  document.readyState === 'loading'
    ? document.addEventListener('DOMContentLoaded', init)
    : setTimeout(init, 80);
})();
</script>

    <section class="book-cta">
    <div class="container">
        <h2 class="heading">
            Want to publish <br>
            your very own book?
        </h2>
        <h3>Our ghostwriters never run out of relevant content for you, Book Spire Publishing has served a variety of clients including, established authors, aspiring authors, large
            and small businesses, and more.
        </h3>
        <div class="btn-block">
            <a href="javascript:" class="btn btn-black various" data-fancybox="" data-src="#popupform">Get a Free
                Quote</a>
            <a href="javascript:" class="btn btn-transparent chat">Live Chat</a>
        </div>
    </div>
</section>

<style>
    .foo_box a h3 {
        font-size: 30px;
        color: black;
    }

    .foo_box a p {
        font-size: 14px;
        margin-top: 12px;
    }

    .foo_box {
        border-right: 1px dotted #0d0d0d;
        padding: 50px;
    }

    .foo_box a h3 i {
        color: #00838c;
    }
</style>

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="foo_box">
                    <a href="mailto:info@bookspirepublishing.com">
                        <h3><i class="fa fa-envelope" aria-hidden="true"></i> Email</h3>
                        <p>info@bookspirepublishing.com</p>
                    </a>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="foo_box">
                    <a href="https://maps.google.com/?q=5900+Balcones+Drive+STE+100+Austin+Texas+78731">
                        <h3><i class="fa fa-globe" aria-hidden="true"></i> Contact Us</h3>
                        <p>5900 Balcones Drive STE 100, Austin, Texas, 78731</p>
                    </a>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="foo_box">
                    <a href="tel:+12137841841">
                        <h3><i class="fa fa-phone-square" aria-hidden="true"></i> Phone</h3>
                        <p>+1 (213) 784-1841</p>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

<?php include 'includes/footer.php'; ?>
